Todo.Web/Controllers/ListItemController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Todo.Common;
using Todo.Data;
using Todo.Services;
using Todo.Web.Context;
using Todo.Web.ViewModels;
using Todo.Web.ViewModels.Extensions;

namespace Todo.Web.Controllers
{
    [SessionAuthorize]
    public class ListItemController : Controller
    {
        private readonly IContext _context;
        private readonly ISaveListItemService _saveListItemService;
        private readonly IDeleteService _deleteService;
        private readonly ISessionContext _sessionContext;

        public ListItemController(ISaveListItemService saveListItemService, IContext context, IDeleteService deleteService,
            ISessionContext sessionContext)
        {
            _saveListItemService = saveListItemService;
            _context = context;
            _deleteService = deleteService;
            _sessionContext = sessionContext;
        }

        [HttpGet]
        public ActionResult Create(Guid listId)
        {
            return View(new CreateListItemViewModel
            {
                ListId = listId
            });
        }

        [HttpPost]
        public async Task<ActionResult> Create(Guid listId, CreateListItemViewModel createRequest)
        {
            if (!ModelState.IsValid)
                return View(createRequest);

            await _saveListItemService.CreateListItem(listId,
                createRequest, _sessionContext.CurrentUser.Id);

            return RedirectToAction("View", "List", new { id = listId });
        }

        [HttpGet]
        public async Task<ActionResult> View(Guid id)
        {
            var listItem = await _context.ListItems.FirstOrDefaultAsync(x => x.Id == id);
            if (listItem == null)
                return HttpNotFound();

            return View(listItem.AsViewModel());
        }

        [HttpGet]
        public async Task<ActionResult> Delete(Guid id)
        {
            var listItem = await _context.ListItems.FirstOrDefaultAsync(x => x.Id == id);
            if (listItem == null)
                return HttpNotFound();

            return View(listItem.AsViewModel());
        }

        [HttpPost]
        public async Task<ActionResult> ExecDelete(Guid id)
        {
            try
            {
                var listItemDeleted = await _deleteService.DeleteListItem(id, _sessionContext.CurrentUser.Id);
                return RedirectToAction("View", "List", new { id = listItemDeleted.ParentListId });
            }
            catch (ResourceSharingException)
            {
                return View("Error");
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit(Guid id)
        {
            var listItem = await _context.ListItems.FirstOrDefaultAsync(x => x.Id == id);
            if (listItem == null)
                return HttpNotFound();

            return View(listItem.AsEditViewModel());
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Guid id, EditTodoListItemViewModel editRequest)
        {
            try
            {
                var itemEdited = await _saveListItemService.UpdateListItem(id, editRequest, _sessionContext.CurrentUser.Id);

                return RedirectToAction("View", new { id });
            }
            catch (ResourceSharingException)
            {
                return View("Error");
            }
        }
    }
}

Todo.Web/Views/ListItem/Create.cshtml
@model Todo.Web.ViewModels.CreateListItemViewModel

@{
    ViewBag.Title = "Create new List Item";
}

<h2>Create new List Item</h2>

@using (Html.BeginForm("Create", "ListItem", new { listId = Model.ListId }, FormMethod.Post, null))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateListItemViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "View", "List", new { id = Model.ListId }, null)
</div>

Todo.Web/Views/ListItem/Delete.cshtml
@model Todo.Web.ViewModels.TodoListItemViewModel

@{
    ViewBag.Title = "Confirm Delete of List Item";
}

<h2>Really Delete @Model.Name?</h2>
<div>
    @using (Html.BeginForm("ExecDelete", "ListItem", new { id = Model.Id }, FormMethod.Post, null))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "View", "List", new { id = Model.ListId }, null)
        </div>
    }
</div>

Todo.Web/Views/ListItem/Edit.cshtml
@model Todo.Web.ViewModels.EditTodoListItemViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>EditTodoListItemViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.IsComplete, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsComplete, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsComplete)
                @Html.ValidationMessageFor(model => model.IsComplete, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Todo.Web/Views/ListItem/View.cshtml
@model Todo.Web.ViewModels.TodoListItemViewModel

@{
    ViewBag.Title = $"Viewing Item: {Model.Name}";
}

<h2>Viewing @Model.Name</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompletedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompletedOn)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "View", "List", new { id = Model.ListId }, null)
</p>