Todo.Web/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Todo.Services;
using Todo.Web.Context;
using Todo.Web.ViewModels;

namespace Todo.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthenticateUserService _authenticateUserService;
        private readonly ISessionContext _sessionContext;

        public AuthController(IAuthenticateUserService authenticateUserService, ISessionContext sessionContext)
        {
            _authenticateUserService = authenticateUserService;
            _sessionContext = sessionContext;
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginViewModel loginRequest)
        {
            if (!ModelState.IsValid)
            {
                loginRequest.Password = string.Empty;
                return View(loginRequest);
            }

            var authedUser = await _authenticateUserService.GetUserByUsernameAndPassword(
                loginRequest.Username,
                loginRequest.Password);

            if (authedUser != null)
            {
                _sessionContext.CurrentUser = authedUser;

                return RedirectToAction("Index", "List");
            }
            else
            {
                ModelState.AddModelError("OperationResult", "Username/Password combination not valid");
                loginRequest.Password = string.Empty;

                return View(loginRequest);
            }
        }

        [HttpGet]
        public ActionResult Logout()
        {
            if (_sessionContext.CurrentUser == null)
                return RedirectToAction("Index", "Main");

            return View();
        }

        [HttpPost]
        public ActionResult ExecLogout()
        {
            _sessionContext.CurrentUser = null;
            return RedirectToAction("Login");
        }
    }
}

Todo.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Todo.Common;
using Todo.Services;
using Todo.Web.Context;
using Todo.Web.ViewModels;

namespace Todo.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly ICreateUserService _createUserService;
        private readonly ISessionContext _sessionContext;

        public UserController(ICreateUserService createUserService, ISessionContext sessionContext)
        {
            _createUserService = createUserService;
            _sessionContext = sessionContext;
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateUserViewModel createUserRequest)
        {
            if (!ModelState.IsValid)
            {
                return View(createUserRequest);
            }

            try
            {
                // create the user
                var newUser = await _createUserService.CreateUser(createUserRequest);
                _sessionContext.CurrentUser = newUser;

                return RedirectToAction("Index", "List");
            }
            catch (DuplicateUserException)
            {
                ModelState.AddModelError("Username", "Username already in use");
                return View(createUserRequest);
            }
        }
    }
}

Todo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Super Todoer", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (SessionContext.Current.CurrentUser != null)
                    {
                    <li>@Html.ActionLink("My Lists", "Index", "List")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (SessionContext.Current.CurrentUser == null)
                    {
                        <li>@Html.ActionLink("Login", "Login", "Auth")</li>
                        <li>@Html.ActionLink("Sign up", "Create", "User")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Logout", "Logout", "Auth")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>